services:
  topic_creator:
    build:
      context: ./topic-creator
    depends_on:
      - broker
    environment:
      - KAFKA_ADDRESS=broker:29092

  step_0_ingestion:
    build:
      context: ./step0-ingestor
    ports:
      - 8080:8000
    depends_on:
      - broker
      - topic_creator
    environment:
      - KAFKA_ADDRESS=broker:29092
      - INGESTION_DATA_DIR=/app/data
      - INGESTION_TOPIC=step0-ingestion

  step_01_a_wfh:
    build:
      context: ./step1.a-wfh
    depends_on:
      - broker
      - topic_creator
    environment:
      - KAFKA_ADDRESS=broker:29092
      - STEP_01_A_WFH_TOPIC_INPUT_NAME=step0-ingestion
      - STEP_01_A_WFH_TOPIC_OUTPUT_NAME=step01-a-wfh

  database_sink:
    build:
      context: ./DbSink
    depends_on:
      - broker
      - topic_creator
    environment:
      - KAFKA_ADDRESS=broker:29092
    volumes:
      - ./db.sqlite:/app/db.sqlite

  broker:
    image: apache/kafka:latest
    hostname: broker
    container_name: broker
    restart: unless-stopped
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:29093
      KAFKA_LISTENERS: PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Q
    volumes:
      - ./scripts/create-topics.sh:/opt/kafka/bin/create-topics.sh

  kafka-ui:
    image: kafbat/kafka-ui:main
    ports:
      - 8081:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: "true"
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker:29092
    depends_on:
      - broker
